services:
  db:
    image: mongo:7.0.1-jammy
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - type: bind
        source: ./database/init/
        target: /docker-entrypoint-initdb.d/
        read_only: true
